(function(){
    'use strict';

    /**
     * This is a sample directive spec
     * Generated by ngappgen Yeomen/Angular generator.
     *
     * @author: Tapas Jena
     * @copyright: Anitech Consulting Services Pvt Ltd.
     */
    describe('<%= _.camelize(name) %>', function() {

      beforeEach(module('<%= appname %>'));

      var scope, compile;

      beforeEach(inject(function($rootScope,$compile) {
        scope = $rootScope.$new();
        compile = $compile;
      }));

      //TODO: Implement your directive spec logic here
      it('should ...', function() {

        /*
        To test your directive, you need to create some html that would use your directive,
        send that through compile() then compare the results.

        var element = compile('<div mydirective name="name">hi</div>')(scope);
        expect(element.text()).toBe('hello, world');
        */

      });
    });

})();
