(function(){
    'use strict';

    /**
     * This is a sample directive
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Tapas Jena
     * @copyright: Anitech Consulting Services Pvt Ltd.
     */
    angular.module('<%= appname %>').directive('<%= _.camelize(name) %>', function() {

        //TODO: Implement your directive logic here
        return {
            restrict: 'A',
            link: function(scope, element, attrs, fn) {

            }
        };

    });

})();
