(function(){
    'use strict';

    /**
     * This is a sample controller
     * Generated by ngappgen Yeomen/Angular generator.
     *
     * @author: Tapas Jena
     * @copyright: Anitech Consulting Services Pvt Ltd.
     */
    angular.module('<%= appname %>').controller('<%= _.camelize(name) %>', ['$scope', function($scope) {

        //TODO: Implement your controller logic here
        $scope.message = 'Bang Bang! Your application is up and running.';

    }]);

})();
