(function(){
    'use strict';

    /**
     * This is a sample controller
     * Generated by ngappgen Yeomen/Angular generator.
     *
     * @author: Tapas Jena
     * @copyright: Anitech Consulting Services Pvt Ltd.
     */
    angular.module('<%= appname %>').controller('<%= _.camelize(name) %>', function() {
        return function(input, arg) {
            return 'output';
        };
    });

})();
