(function(){
    'use strict';

    /**
     * This is a sample filter
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Tapas Jena
     * @copyright: Anitech Consulting Services Pvt Ltd.
     */
    angular.module('<%= appname %>').filter('<%= _.camelize(name) %>', function($scope) {

        //TODO: Implement your filter logic here
        return function(input,arg) {
            return 'output';
        };

    });

})();
