(function(){
    'use strict';

    /**
     * This is a sample filter spec
     * Generated by ngappgen Yeomen/Angular generator.
     *
     * @author: Tapas Jena
     * @copyright: Anitech Consulting Services Pvt Ltd.
     */
    describe('<%= _.camelize(name) %>', function() {

        beforeEach(module('<%= appname %>'));

        //TODO: Implement your filter spec logic here
        it('should ...', inject(function($filter) {

            var filter = $filter('<%= _.camelize(name) %>');

            expect(filter('input')).toEqual('output');

        }));

    });

})();
