(function(){
    'use strict';

    /**
     * This is a sample filter spec
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Tapas Jena
     * @copyright: Anitech Consulting Services Pvt Ltd.
     */
    describe('<%= _.camelize(name) %>', function() {

        beforeEach(module('<%= appname %>'));

        it('should ...', inject(function($filter) {

            //TODO: Implement your filter spec logic here
            var filter = $filter('<%= _.camelize(name) %>');
            expect(filter('input')).toEqual('output');

        }));

    });

})();
