(function(){
    'use strict';

    /**
     * This is a sample filter spec
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Tapas Jena
     * @copyright: Anitech Consulting Services Pvt Ltd.
     */
    describe('<%= _.camelize(name) %>', function() {

        var filter;

        beforeEach(function() {
            module('<%= appname %>');

            inject(function($filter) {
                filter = $filter('<%= _.camelize(name) %>');
            });
        });

        it('should ...', function() {

            //TODO: Implement your filter spec logic here
            //expect(filter('input')).toEqual('output');

        });

    });

})();
