/**
 * This is a sample service
 * Generated by ngappgen Yeomen/Angular generator.
 *
 * @author: Tapas Jena
 * @copyright: Anitech Consulting Services Pvt Ltd.
 */
angular.module('<%= appname %>').factory('<%= _.camelize(name) %>',function() {

	var <%= _.camelize(name) %> = {};

	return <%= _.camelize(name) %>;
});
