/**
 * This is a sample service spec
 * Generated by ngappgen Yeomen/Angular generator.
 *
 * @author: Tapas Jena
 * @copyright: Anitech Consulting Services Pvt Ltd.
 */
describe('<%= _.camelize(name) %>', function() {

  beforeEach(module('<%= appname %>'));

  it('should ...', inject(function(<%= _.camelize(name) %>) {

	//expect(<%= _.camelize(name) %>.doSomething()).toEqual('something');

  }));

});
