(function(){
    'use strict';

    /**
     * This is a sample service
     * Generated by ngappgen Yeomen/Angular generator.
     *
     * @author: Tapas Jena
     * @copyright: Anitech Consulting Services Pvt Ltd.
     */
    angular.module('<%= appname %>').service('<%= _.camelize(name) %>', ['$http', function($http) {

        //TODO: Implement your service logic here
        this.getMessage = function(){
            return 'Bang Bang! Your application is up and running.';
        };

    }]);

})();
