(function(){
    'use strict';

    /**
     * This is a sample directive
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Tapas Jena
     * @copyright: Anitech Consulting Services Pvt Ltd.
     */
    angular.module('<%= appname %>').directive('<%= _.camelize(name) %>', function() {

        //TODO: Implement your complex directive logic here
        return {
            restrict: 'E',
            replace: true,
            scope: {

            },
            templateUrl: '<%= htmlPath %>',
            link: function(scope, element, attrs, fn) {

            }
        };

    });

})();
