(function(){
    'use strict';

    /**
     * This is a sample directive spec
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Tapas Jena
     * @copyright: Anitech Consulting Services Pvt Ltd.
     */
    describe('<%= _.camelize(name) %>', function() {

        var scope, compile;

        beforeEach(module('<%= appname %>'));

        beforeEach(inject(function($rootScope,$compile) {
            scope = $rootScope.$new();
            compile = $compile;
        }));

        it('should ...', function() {

            //TODO: Implement your complex directive spec logic here
            /*
            To test your directive, you need to create some html that would use your directive,
            send that through compile() then compare the results.

            var element = compile('<div mydirective name="name">hi</div>')(scope);
            expect(element.text()).toBe('hello, world');
            */

        });

    });

})();
