(function(){
    'use strict';

    /**
     * This is a sample module for all application level common tasks
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Tapas Jena
     * @copyright: Anitech Consulting Services Pvt Ltd.
     */
    angular.module('common', ['ui.bootstrap', 'ui.utils', '<%= routerModuleName %>', 'ngAnimate', 'restangular']);
    <% if (!uirouter) { %>
    angular.module('common').config(function($routeProvider) {

        /* Add New Routes Above */

    });
    <% } %><% if (uirouter) { %>
    angular.module('common').config(function($stateProvider) {

        /* Add New States Above */

    });
    <% } %>

})();
