(function(){
    'use strict';

    /**
     * This is a sample template
     * Generated by ngappgen Yeomen/Angular generator.
     *
     * @author: Tapas Jena
     * @copyright: Anitech Consulting Services Pvt Ltd.
     */
    angular.module('<%= appname %>').controller('<%= ctrlname %>',function($scope){


    });

})();
